oskoperator/osko

helm/osko/.helmignore, helm/osko/Chart.yaml, helm/osko/templates/NOTES.txt, helm/osko/templates/_helpers.tpl, helm/osko/templates/cluster-role-binding.yaml, helm/osko/templates/cluster-role.yaml, helm/osko/templates/deployment.yaml, helm/osko/templates/hpa.yaml, helm/osko/templates/leader_election_role.yaml, helm/osko/templates/leader_election_role_binding.yaml, helm/osko/templates/prometheusrule_editor_role.yaml, helm/osko/templates/prometheusrule_editor_role_binding.yaml, helm/osko/templates/serviceaccount.yaml, helm/osko/templates/tests/test-connection.yaml, helm/osko/values.yaml
Definitely not complete HELM Chart. A lot of RBAC stuff is missing for now.
=> feat(helm): basic helm chart

cmd/main.go, internal/controller/openslo/slo_controller.go, internal/utils/common_utils.go
- enable event recording for SLOs
- record events during SLO lifecycle
- minor fixes and changes
=> feat(slo): enable event recording

cmd/main.go, config/rbac/role.yaml, helm/osko/templates/cluster-role.yaml, internal/controller/osko/mimirrule_controller.go
- change leader electio id suffix from openslo to osko
=> fix(rbac): RBAC api group fixes

helm/osko/Chart.yaml, helm/osko/values.yaml
- add osko-crds dependency
- add prometheus-operator-crds dependency
- solve #42
=> feat(helm): Add Helm chat dependencies

internal/controller/openslo/slo_controller.go, internal/controller/osko/mimirrule_controller.go, internal/utils/common_utils.go
simplify/standardize finalizers handling, remove unnecessary functions
=> refactor(controller): handling of finalizers

internal/controller/monitoring.coreos.com/prometheusrule_controller.go
This allows us to start managing externally created PrometheusRules using osko.
=> feat(prometheusrule_controller): manage if manage label set

internal/helpers/prometheus_helper.go
=> fix(slo): missing target for 28d

internal/controller/openslo/slo_controller.go, internal/controller/osko/mimirrule_controller.go, internal/helpers/prometheus_helper.go
- fill status and Ready field when MimirRule successfully created.
=> feat(mimirrule): add mimirrule events and status

cmd/main.go, internal/controller/monitoring.coreos.com/prometheusrule_controller.go, internal/controller/openslo/slo_controller.go, internal/controller/osko/mimirrule_controller.go
Fixes https://github.com/oskoperator/osko/issues/59
=> Fix PrometheusRule reconcile on SLO change

internal/controller/openslo/slo_controller.go
Fixes https://github.com/oskoperator/osko/issues/66
=> fix(slo_controller): datasource application race condition

internal/helpers/prometheus_helper.go
- whatewer label will be prefixed with `osko.dev/` will be processed and passed to PrometheusRule and MimirRule as a metric label
=> feat(labels): support additional labels

internal/controller/monitoring.coreos.com/prometheusrule_controller.go, internal/helpers/prometheus_helper.go
=> fix(prometheusrule): compare to SLO object

internal/helpers/prometheus_helper.go
=> feat(promrule): configurable base window

internal/controller/osko/mimirrule_controller.go
=> fix(mimirclient): init client earlier in reconcile

internal/helpers/prometheus_helper.go
=> feat(promql): switched from good to bad base

cmd/main.go, internal/config/config.go, internal/config/types.go, internal/config/utils.go
closes https://github.com/oskoperator/osko/issues/100
=> feat(config): default configuration and optional config via env

internal/helpers/prometheus_helper.go
=> fix(promql): add missing prefix to bad rule

internal/helpers/prometheus_helper.go
Fix the SLI measurement to get the success rate from the failure rate
=> fix(promql): another fix for bad

helm/osko/Chart.yaml, helm/osko/templates/cluster-role.yaml
=> feat(rbac): add missing rbac

config/samples/openslo_v1_slo.yaml, docs/labels-and-annotations.md, internal/controller/osko/mimirrule_controller.go, internal/helpers/mimirtool_helper.go, internal/helpers/prometheus_helper.go
=> feat(magic-alerts): Basic recording rules for alerting

Makefile
when deploying dev infratructure
=> feat(make): make wait for services better

internal/controller/osko/alertmanagerconfig_controller.go
=> fix(alertmanagerconfig): proper api delete
